dist: bionic
addons:
  apt:
    # System conda installation: https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html
    sources:
      - sourceline: 'deb https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main'
        key_url: https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
    packages:
      - conda

language: python

jobs:
  include:
    - python: 3.6
    - python: 3.7

install:

  # Enable conda
  - sudo rm -rf ~/.conda # Fix a conda glitch
  - /opt/conda/bin/conda init bash
  - . ~/.bashrc
  - conda info

script:

  # Set version
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then export BUILD_VERSION=$TRAVIS_TAG; else export BUILD_VERSION=0.0.0; fi
  - export BUILD_NUMBER=0

  # Create a build enviroment
  - conda create -n build -y conda-build
  - conda activate build

  # Build a conda package
  - python ci/travis/insert_placeholder_values.py
  - conda build --python $TRAVIS_PYTHON_VERSION --no-include-recipe
                -c acellera -c psi4 -c conda-forge
                package/parameterize

  # Create a test environment
  - conda create -n test -y
                 -c acellera -c psi4 -c conda-forge
                 --file DEPENDENCIES
                 codecov
                 coverage
                 pytest>=5
                 python=$TRAVIS_PYTHON_VERSION
  - conda activate test

  # Install the conda package
  - conda install -y ~/.conda/envs/build/conda-bld/linux-64/parameterize-*.tar.bz2

  # Run tests
  - coverage run -m pytest --doctest-modules --verbose parameterize/*.py parameterize/*/*.py

after_success:

  # Upload coverage statistics
  - codecov

before_deploy:

  # Create a deployment enviroment
  - conda create -n deploy -y anaconda-client
  - conda activate deploy

deploy:
  - provider: script
    script: anaconda -t $ANACONDA_TOKEN_BASIC upload -u acellera ~/.conda/envs/build/conda-bld/linux-64/parameterize-*.tar.bz2
    on:
      tags: true
      branch: master