dist: bionic
addons:
  apt:
    # System conda installation: https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html
    sources:
      - sourceline: 'deb https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main'
        key_url: https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
    packages:
      - conda

language: python

jobs:
  include:
    - os: linux
      python: 3.6
      env: OSNAME=Linux CONDA_PY=3.6
    - os: linux
      python: 3.7
      env: OSNAME=Linux CONDA_PY=3.7

env:
  global:
    - PYTHONHASHSEED=0

before_install:
  # Enable conda
  - /opt/conda/bin/conda init bash
  - . ~/.bashrc
  - conda info

script:

  # Set version
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then export BUILD_VERSION=$TRAVIS_TAG; else export BUILD_VERSION=0.0.0; fi
  - echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
  - echo "TRAVIS_TAG    = $TRAVIS_TAG"
  - echo "TRAVIS_PULL_REQUEST = $TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_REPO_SLUG = $TRAVIS_REPO_SLUG"
  - echo "BUILD_VERSION = $BUILD_VERSION"
  # Always set it to 0 so we don't get a new release at every successful commit
  - export BUILD_NUMBER=0

  # Create a build enviroment
  - conda create -n build -y conda-build
  - conda activate build

  # Build a conda package
  - python ci/travis/insert_placeholder_values.py
  - conda build --python $TRAVIS_PYTHON_VERSION package/parameterize --no-include-recipe -c acellera -c psi4 -c conda-forge

  # Create a test environment
  - conda create -n test -y -c acellera -c psi4 -c conda-forge
                 --file DEPENDENCIES python=$TRAVIS_PYTHON_VERSION
  - conda activate test

  # Install the conda package
  - conda install -y ~/.conda/envs/build/conda-bld/linux-64/parameterize-*.tar.bz2

  # Run tests
  - pip install -q codecov coverage
  - coverage run -m unittest discover --start-directory parameterize --pattern "*.py"

after_success:

  # Upload coverage statistics
  - codecov

deploy:
  - provider: script
    cleanup: false
    script: bash ci/travis/deploy.sh
    on:
      tags: true
      branch: master