package:
  name: parameterize
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: 0
  entry_points:
    - parameterize = parameterize.parameterization.cli:main_parameterize

requirements:
  build:
    - python 
    - requests
    
  run:
    - python 
DEPENDENCY_PLACEHOLDER

about:
  home: https://www.acellera.com
  license: "HTMD Software License version 1.1"
  license_file: HTMD_LICENCE.txt
